version: '3'
services:

  mongodb:
    image: mongo
    ports:
    - 27017:27017

  tweet_collector:
    build: tweet_collector/
    volumes:
    - ./tweet_collector/:/app
    depends_on:
    - mongodb
    env_file:
    - .env

  postgresdb:
    image: postgres
    ports:
    - 5555:5432
    environment:
    - POSTGRES_USER=em
    - POSTGRES_PASSWORD=Emiliepostgres01!
    - POSTGRES_DB=twitter


  etl:
    build: etl_job/
    volumes:
    - ./etl_job/:/app
    depends_on:
    - mongodb
    - postgresdb
    env_file:
    - .env

  slack:
    build: slackbot/
    volumes:
    - ./slackbot/:/app
    depends_on:
    - mongodb
    - postgresdb
    env_file:
    - .env